### ISSUE TITLE
Cornelius runs into Hettie

### ISSUE THREAD

**Issue by ChaelCodes** [ChaelCodes/CorneliusCodes#2]
# Description
Cornelius keeps running into Hettie (and it's only chapter 1 😳) Let's prevent Cornelius from running into Hettie, when they can.
![Cornelius-and-Hettie run into each other... head first](https://user-images.githubusercontent.com/8124558/134245564-6ff45291-085e-47e4-88e7-7f9dc39772e4.gif)

**Comment by PinkFlufflyLlama** [comment]
This could be an extension of the solution of #6 as a similar solution of creating a list of illigal squares could be applied

**Comment by ChaelCodes** [comment]
> This could be an extension of the solution of #6 as a similar solution of creating a list of illigal squares could be applied

Good point!

**Comment by ChaelCodes** [comment]
Cornelius still headbutts other snakes. Let's mark the squares around their head as invalid, IF they're same size or bigger than Corny.
