### ISSUE TITLE
Cornelius runs into their own body

### ISSUE THREAD

**Issue by ChaelCodes** [ChaelCodes/CorneliusCodes#6]
# Description
Cornelius runs into their own body. This is because we only check if the neck is occupying the space we want to go to. We don't check if the body is occupying that spot.
![no walls cornelius 2](https://user-images.githubusercontent.com/8124558/134268111-e231b208-7ebe-446c-a3da-fd87044ee371.gif)

Additional research (comments below) indicates this may because Cornelius is hungry and confusing their body for prey.

**Comment by ChaelCodes** [comment]
@PinkFlufflyLlama GREAT POINT!! Cornelius seems very excited/confused. I bet that's why they're biting themself.

**Comment by PinkFlufflyLlama** [comment]
Yeah, I think they may need a list made to help them keep track of where their tail so they know not to run into it in the heat of the moment
